<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>iTunesArtworkEditor</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyTitle>iTunes Artwork Editor</AssemblyTitle>
    <Description>iTunes Artwork Editor</Description>
    <Company>Joshhhuaaa</Company>
	<Copyright>Copyright © 2026 Joshhhuaaa</Copyright>
    <Product>iTunes Artwork Editor</Product>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.ico" />
  </ItemGroup>

</Project>
